//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EtWorldPainter.rc
//
#define ID_ENVI_SAVE                    0
#define IDC_BACK                        3
#define IDR_PROPPOOL                    4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_DK_BRUSHVIEW_1               101
#define ID_DK_BRUSHVIEW_2               102
#define IDD_BRUSHPANEVIEW               103
#define ID_DK_BRUSHVIEW_3               103
#define IDD_RENDERVIEW                  104
#define ID_DK_BRUSHVIEW_4               104
#define IDD_LAYERPANEVIEW               105
#define ID_DK_BRUSHVIEW_H               105
#define IDD_LAYERPREVVIEW               106
#define ID_DK_BRUSHVIEW_D               106
#define IDD_GRIDINFOPANEVIEW            107
#define ID_INDICATOR_DESC               107
#define IDD_LOGINLISTPANEVIEW           108
#define ID_INDICATOR_PROG               108
#define IDD_DUMMYVIEW                   109
#define IDD_BRUSHRENDERVIEW             110
#define IDD_CAMERAPANEVIEW              111
#define IDD_LAYERHEIGHTVIEW             112
#define IDD_SECTORINFOPANEVIEW          113
#define IDD_BLOCKGROUPPANEVIEW          114
#define IDD_TILEMANAGERPANEVIEW         115
#define IDD_RANDOMDUNGEONRENDERVIEW     116
#define IDD_RANDOMDUNGEONDEFAULTPANEVIEW 117
#define IDD_PROPRENDERVIEW              118
#define IDD_MANAGEREXPLORERPANEVIEW     119
#define IDD_SKINMANAGERPANEVIEW         120
#define IDD_FILTERPANEVIEW              123
#define IDD_PORPPOOLPANEVIEW            124
#define IDD_PROPPOOLVIEW                125
#define IDD_PROPPOOLPROPERTIESVIEW      126
#define IDD_PROPPROPERTIESPANEVIEW      127
#define IDR_MAINFRAME                   128
#define IDR_EtWorldPainterTYPE          129
#define IDB_PANEICON                    130
#define IDB_BRUSHDEF1                   131
#define IDB_BRUSHDEF2                   132
#define IDB_BRUSHDEF3                   133
#define IDB_BRUSHDEF4                   134
#define IDB_BRUSHDEF5                   135
#define IDB_BRUSHDEF6                   136
#define IDB_BRUSHDEF7                   137
#define IDB_BRUSHDEF8                   138
#define IDD_ENVIPANEVIEW                139
#define IDB_BITMAP1                     140
#define IDB_ADOBETABITEM                140
#define IDD_CONNECT_SETTING             141
#define IDD_ADMIN                       142
#define IDR_CONTEXTMENU                 143
#define IDD_CREATEENVIDLG               144
#define IDD_ENVIBASEPANEVIEW            145
#define IDR_DEFAULTDDS                  146
#define IDD_ENVILIGHTPANEVIEW           147
#define IDR_TEXTURELIST                 148
#define IDD_EVENTRENDERVIEW             149
#define IDR_TEMP                        150
#define IDR_ACTIONTOOLBAR               151
#define IDR_SIMULATION                  153
#define IDD_EVENTAREAPANEVIEW           154
#define IDD_EVENTPROPERTIESPANEVIEW     155
#define IDR_DUMMY_MSH                   156
#define IDR_DUMMY_SKN                   157
#define IDR_DDS2                        158
#define IDR_DUMMY_ANI                   158
#define IDB_BITMAP2                     159
#define IDD_SOUNDRENDERVIEW             160
#define IDD_SOUNDMANAGERPANEVIEW        161
#define IDD_IMAGEPREVDLG                162
#define IDD_DIALOG1                     163
#define IDD_TEXTUREPREV_DLG             164
#define IDR_SKINLIST                    165
#define IDD_SOUNDLISTPANEVIEW           166
#define IDD_SOUNDPROPERTYPANEVIEW       167
#define IDD_LAYERGRASSVIEW              168
#define IDD_CREATEGRID                  169
#define IDD_DELETEGRID                  170
#define IDD_NAVIRENDERVIEW              171
#define IDD_SKINPREVDLG                 172
#define IDR_ENVI_TOOLBAR                173
#define IDD_NAVIPROPERTYPANEVIEW        174
#define IDB_ENVIICON                    175
#define IDR_EVENTLIST                   176
#define IDR_SOUNDLIST                   178
#define IDB_SOUNDICON                   180
#define IDD_SOUNDPREVDLG                181
#define IDD_RENDEROPTIONPANEVIEW        182
#define IDR_SPEAKERSKN                  183
#define IDR_SPEAKERMSH                  184
#define IDR_SPEAKERDDS                  185
#define IDB_SOUNDTREEICON               186
#define IDD_PROPERTIESDLG               187
#define IDR_GRASSLIST                   188
#define IDD_TRIGGERRENDERVIEW           189
#define IDR_GRASSDDS                    190
#define IDR_ATTRLIST                    191
#define IDD_PROPLISTPANEVIEW            192
#define IDD_TRIGGERPANEVIEW             193
#define IDR_LIGHT_SKN                   194
#define IDR_LIGHT_DDS                   195
#define IDR_DDS4                        196
#define IDR_LIGHT_MSH                   196
#define IDD_TRIGGERPROPERTIESPANEVIEW   197
#define IDB_BITMAP3                     198
#define IDD_TRIGGERSELECT               199
#define IDD_PARAMINPUTDLG               200
#define IDD_MOVEGRIDDLG                 201
#define IDR_SKINLIST2                   202
#define IDD_MAKEMINIMAP                 204
#define IDD_TRIGGERATTRIBUTEPANEVIEW    205
#define IDD_WATERRENDERVIEW             206
#define IDB_BITMAP4                     206
#define IDD_WATERPANEVIEW               207
#define IDR_WATER_TOOLBAR               207
#define IDD_WATERPROPPANEVIEW           208
#define IDD_CREATEEVENTDLG              209
#define IDD_EVENTEDIT_SELEDITTYPE       210
#define IDD_EVENTEDIT_CREATEMODIFY_EVENT 211
#define IDD_EVENTEDIT_SELECTEVENT       212
#define IDD_EVENTEDIT_FINISH            213
#define IDD_EVENTEDIT_SELECTPARAMETER   214
#define IDD_EVENTEDIT_CREATEMODIFY_PARAMETER 215
#define IDB_BITMAP5                     216
#define IDB_EVENTWIZARDIMAGE            216
#define IDD_TRIGGERVALUEDEFINEPANEVIEW  217
#define IDD_TRIGGERVALUEDLG             218
#define IDD_LAYERDECALVIEW              219
#define IDD_PROFILEDLG                  220
#define IDB_BITMAP6                     221
#define IDD_NEWPROFILEDLG               222
#define IDD_NATIONDLG                   223
#define IDB_BITMAP7                     224
#define IDB_BITMAP8                     225
#define IDB_BITMAP9                     226
#define IDD_CONNECTTODLG                227
#define IDD_CREATEPROPPROPERTYDLG       228
#define IDB_PROPWIZARDIMAGE             229
#define IDD_PROPEDIT_SELEDITTYPE        230
#define IDD_PROPEDIT_SELECTTYPE         231
#define IDD_PROPEDIT_CREATEPARAMETER    232
#define IDD_PROPEDIT_SELECTPARAMETER    233
#define IDD_PROPEDIT_FINISH             234
#define IDD_PROPEDIT_CREATETYPE         235
#define IDD_EXPORTPORPINFODLG           236
#define IDD_GRIDLISTPANEVIEW            237
#define IDD_TRIGGEROPERATORDLG          238
#define IDD_GRIDDESCRIPTIONPANEVIEW     239
#define IDB_BITMAP10                    241
#define IDD_DIALOG2                     242
#define IDD_PRELOGO                     242
#define IDR_DDS1                        244
#define IDR_CAMERA_SKN                  244
#define IDR_CAMERA_MSH                  245
#define IDD_DECALLISTPANEVIEW           246
#define IDD_IGNOREPROPFOLDERDLG         247
#define IDR_RELOAD                      248
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON9                     1002
#define IDC_BUTTON10                    1003
#define IDC_BUTTON3                     1004
#define IDC_BUTTON4                     1005
#define IDC_BUTTON11                    1005
#define IDC_BUTTON5                     1006
#define IDC_BUTTON6                     1007
#define IDC_BUTTON7                     1008
#define IDC_BUTTON8                     1009
#define IDC_EDIT1                       1014
#define IDC_EDIT4                       1015
#define IDC_EDIT5                       1016
#define IDC_LIST1                       1016
#define IDC_EDIT6                       1017
#define IDC_EDIT8                       1018
#define IDC_EDIT10                      1019
#define IDC_RADIAN                      1022
#define IDC_SLIDER_NEAR                 1023
#define IDC_SLIDER_FAR                  1024
#define IDC_STATIC_PREV                 1024
#define IDC_SLIDER_FOV                  1025
#define IDC_SLIDER_CAMSPEED             1026
#define IDC_TREE1                       1026
#define IDC_RADIO1                      1027
#define IDC_RADIO2                      1028
#define IDC_RADIO3                      1029
#define IDC_RADIO4                      1030
#define IDC_HARDNESS                    1031
#define IDC_RADIO5                      1031
#define IDC_DIAMETER                    1032
#define IDC_RADIO6                      1032
#define IDC_HEIGHT                      1033
#define IDC_RADIO7                      1033
#define IDC_STRONG                      1034
#define IDC_CHECK1                      1034
#define IDC_SLIDER1                     1035
#define IDC_CHECK2                      1035
#define IDC_SLIDER2                     1036
#define IDC_CHECK3                      1036
#define IDC_SLIDER3                     1037
#define IDC_EDIT2                       1038
#define IDC_EDIT3                       1039
#define IDC_COMBO1                      1039
#define IDC_EDIT7                       1040
#define IDC_PLAYBUTTON                  1040
#define IDC_COMBO2                      1040
#define IDC_RADIO8                      1041
#define IDC_RICHEDIT21                  1041
#define IDC_COMBO3                      1041
#define IDC_EDIT9                       1041
#define IDC_DESC_STATIC                 1042
#define IDC_RADIO9                      1043
#define IDC_STATIC1                     1043
#define IDC_RADIO10                     1044
#define IDC_STATIC2                     1044
#define IDC_NEXT                        1045
#define IDC_STATIC_PREVIEW              1046
#define IDC_STATIC_ADDITIONAL           1047
#define IDC_STATIC_MIN                  1048
#define IDC_STATIC_MAX                  1049
#define IDC_STATIC_DATA                 1050
#define IDC_STATIC_SLIDER               1051
#define IDC_STATIC_DESC                 1054
#define ID_PROJECT_CONNECT              32771
#define ID_PROJECT_SAVE                 32772
#define ID_PROJECT_SETTING              32773
#define ID_PROJECT_DISCONNECTPROJECT    32774
#define ID_PROJECT_DISCONNECT           32775
#define ID_GRIDCONTEXT_CHECKOUTGRID     32776
#define ID_GRIDCONTEXT_CHECKINGRID      32777
#define ID_GRIDCONTEXT_CHECKOUT         32778
#define ID_GRIDCONTEXT_CHECKIN          32779
#define ID_GRIDCONTEXT_CREATEEMPTYSECTOR 32780
#define ID_GRIDCONTEXT_EMPTYSECTOR      32781
#define ID_TEXTUREADD                   32782
#define ID_TEXTUREREMOVE                32783
#define ID_TEXTUREREFRESH               32784
#define ID_TEXTURE_ID                   32785
#define ID_TEXTURE_ID32786              32786
#define ID_TEXTURE_ID32787              32787
#define ID_TEXTURE_ID32788              32788
#define ID_TEXTUREPREVIEW               32789
#define ID_TEXTURESIZE                  32790
#define ID_TEXTURE_ID32791              32791
#define ID_UNDO                         32794
#define ID_REDO                         32795
#define ID_PROJECT_SAVECURRENTVIEW      32799
#define ID_PROJECT_SAVEVIEW             32800
#define ID_ADDBRUSHSIZE                 32801
#define ID_MINUSBRUSHSIZE               32802
#define ID_REDOACCEL                    32804
#define ID_UNDOACCEL                    32805
#define ID_SIMUL_RUN                    32806
#define ID_SIMUL_STOP                   32807
#define ID_SIMULATION_RUN               32808
#define ID_SIMULATION_STOP              32809
#define ID_MANAGEREXPLORER_CREATENEWFOLDER 32811
#define ID_MANAGEREXPLORER_DELETEFOLDER 32812
#define ID_MANAGEREXPLORER_CREATEFOLDER 32813
#define ID_LAYERPREV_IMPORTTEXTURE      32814
#define ID_LAYERPREV_EXPORTTEXTURE      32815
#define ID_LAYERHEIGHT_IMPORTTEXTURE    32816
#define ID_LAYERHEIGHT_EXPORTTEXTURE    32817
#define ID_32818                        32818
#define ID_TOOLWINDOW_GRIDINFOMATIONWINDOW 32819
#define ID_TOOLWINDOW_LOGINWINDOW       32820
#define ID_TOOLWINDOW_SECTORINFOMATIONWINDOW 32821
#define ID_TOOLWINDOW_CAMERACONTROLWINDOW 32822
#define ID_TOOLWINDOW_BRUSHCONTROLWINDOW 32823
#define ID_TOOLWINDOW_TILEMANAGER       32824
#define ID_TOOLWINDOW_SKINMANAGER       32825
#define ID_TOOLWINDOW_LIGHTMANAGER      32826
#define ID_TOOLWINDOW_COLORADJUSTMENT   32827
#define ID_TOOLWINDOW_MANAGEREXPLORER   32828
#define ID_TOOLWINDOW_FILTERMANAGER     32829
#define ID_SKINADD                      32830
#define ID_SKINREMOVE                   32831
#define ID_SKINREFRESH                  32832
#define ID_SKINPREVIEW                  32833
#define ID_SKINMODE                     32834
#define ID_BUTTON32840                  32840
#define ID_SKINSIZE                     32840
#define ID_POOL_EMPTY                   32843
#define ID_POOL_SAVE                    32844
#define ID_POOL_LOADLIST                32845
#define ID_POOL_EMPTY32846              32846
#define ID_POOL_SAVE32847               32847
#define ID_POOL_LOADLIST32848           32848
#define ID_GRIDCONTEXT_CREATENEWGRID    32849
#define ID_GRIDCONTEXT_DELETECURRENTGRID 32850
#define ID_GRID_CREATEGRID              32851
#define ID_GRID_DELETEGRID              32852
#define ID_ENVI_NEW                     32853
#define ID_ENVI_SAVEAS                  32858
#define ID_ENVI_LOADLIST                32859
#define ID_SKIN                         32860
#define ID_ENVI_NEW32861                32861
#define ID_ENVI_SAVEAS32862             32862
#define ID_ENVI_LOADLIST32863           32863
#define ID_ENVILIGHT_ADDDIRECTIONLIST   32864
#define ID_ENVILIGHT_ADDPOINTLIGHT      32865
#define ID_ENVILIGHT_ADDSPOTLIGHT       32866
#define ID_ENVILIGHT_ASDF               32867
#define ID_ENVILIGHT_REMOVELIGHT        32868
#define ID_ENVILIGHT_ADDDIRECTIONLIGHT  32869
#define ID_ENVI_BAKELIGHTMAP            32872
#define ID_ENVI_BAKELIGHTMAP32873       32873
#define ID_EVENT_LIST                   32874
#define ID_EVENTLIST_EVENTLIST          32875
#define ID_EVENTLIST                    32876
#define ID_PROPERTIES_GRIDOPTION        32877
#define ID_PROPERTIES_EVENTSETTING      32878
#define ID_SOUNDADD                     32880
#define ID_SOUNDREMOVE                  32881
#define ID_SOUNDMODE                    32884
#define ID_SOUNDREFRESH                 32885
#define ID_ENVI_RELOAD                  32886
#define ID_ENVI_RELOAD32887             32887
#define ID_ENVI_DELETE                  32888
#define ID_PROPERTIES_DIRECTORYSETTING  32889
#define ID_GRASS_1                      32890
#define ID_GRASS_2                      32891
#define ID_GRASS_3                      32893
#define ID_GRASS_4                      32894
#define ID_DK_BRUSHVIEW_5               32895
#define ID_GRASS_5                      32897
#define ID_GRASS_6                      32898
#define ID_GRASS_7                      32899
#define ID_GRASS_8                      32900
#define ID_ATTR_1                       32901
#define ID_ATTR_2                       32902
#define ID_ATTR_3                       32903
#define ID_ATTR_4                       32904
#define ID_ATTRIBUTE_1                  32905
#define ID_ATTRIBUTE_2                  32906
#define ID_ATTRIBUTE_3                  32907
#define ID_ATTRIBUTE_4                  32908
#define ID_SKINMANAGER_OPENETVIEWER     32914
#define ID_SKINMANAGER_OPENETACTIONTOOL 32915
#define ID_SKINMANAGER_OPENTOETACTIONTOOL 32916
#define ID_SKINMANAGER_OPENTOETVIEWER   32917
#define ID_TRIGGERLIST_INSERTCATEGORY   32918
#define ID_TRIGGERLIST_INSERTEVENT      32919
#define ID_TRIGGERLIST_ADDCATEGORY      32920
#define ID_TRIGGERLIST_ADDTRIGGER       32921
#define ID_TRIGGERLIST_ASDF             32922
#define ID_TRIGGERLIST_REMOVE           32923
#define ID_TRIGGERLIST_COPY             32924
#define ID_TRIGGERLIST_CUT              32925
#define ID_TRIGGERLIST_PASTE            32926
#define ID_TRIGGERLIST_DELETE           32927
#define ID_TRIGGERPROPERTIES_CUR        32928
#define ID_TRIGGERPROPERTIES_COPY       32929
#define ID_TRIGGERPROPERTIES_PASTE      32930
#define ID_TRIGGERPROPERTIES_DELETE     32931
#define ID_TRIGGERPROPERTIES_ADDCONDITION 32932
#define ID_TRIGGERPROPERTIES_ADDACTION  32933
#define ID_TRIGGERPROPERTIES_CUT        32934
#define ID_TRIGGERPROPERTIES_ASDF       32935
#define ID_TRIGGERPROPERTIES_PROPERTIES 32936
#define ID_GRIDSETTING_MOVEGRID         32937
#define ID_GRID_MOVEGRID                32938
#define ID_TRIGGERPROPERTIES_ADDEVENT   32939
#define ID_BUTTON32940                  32940
#define ID_SKINNAME                     32940
#define ID_TOOLS_MAKEMINIMAP            32941
#define ID_BAKEWATERALPHA               32943
#define ID_WATER_MAKEALPHA              32944
#define ID_WATER_BAKEWATERALPHA         32945
#define ID_WATERBAKEWATERALPHA          32946
#define ID_TRIGGERVALUEDEFINE_ADDVALUE  32947
#define ID_TRIGGERVALUEDEFINE_DELETEVALUE 32948
#define ID_TRIGGERVALUEDEFINE_MODIFYVALUE 32949
#define ID_PROFILEEDIT_ADDNATION        32950
#define ID_PROFILEEDIT_REMOVENATION     32951
#define ID_PROFILEEDIT_MODIFYNATION     32952
#define ID_PROPERTIES_PROPPROPERTYSETTING 32953
#define ID_TOOLS_EXPORTTERRAINTO3DSMAXSCRIPTDATA 32954
#define ID_TOOLS_EXPORTPROPINFOTO3DSMAXSCRIPTDATA 32955
#define ID_TRIGGERPROPERTIES_ADDOPERATOR 32956
#define ID_ADDOPERATOR_OR               32957
#define ID_ADDOPERATOR_RANDOM           32958
#define ID_ATTR_MAKENAVI                32959
#define ID_ATTR_GEN_ATT4                32960
#define ID_BUTTON32961                  32961
#define ID_ATTR_CLEAR_ATT4              32961
#define ID_TOGGLESIMUL                  32962
#define ID_VIEW_TOGGLETOPVIEW           32964
#define ID_VIEW_CAMERA                  32966
#define ID_VIEW_CAMERA_LIGHT            32967
#define ID_RELOAD                       32969
#define ID_LAYER_ID                     32970
#define ID_TOOLS_SAVECURRENTLIGHTMAP    32971
#define ID_TOOLS_SAVELIGHTMAP           32972

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        252
#define _APS_NEXT_COMMAND_VALUE         32973
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           240
#endif
#endif
