#pragma once

#define UM_REFRESH_VIEW WM_USER + 1001
#define UM_CUSTOM_RENDER WM_USER + 1002
#define UM_SELECT_CHANGE_CLOSE_VIEW WM_USER + 1006
#define UM_SELECT_CHANGE_OPEN_VIEW WM_USER + 1005

#define UM_REFRESH_PANE_VIEW WM_USER + 1004

#define UM_TILEPANE_GET_PREVIEW_IMAGE WM_USER + 1007
#define UM_TILEPANE_DROPITEM WM_USER + 1008
#define UM_TILEPANE_DROPMOVEITEM WM_USER + 1009

#define UM_SKINPANE_GET_PREVIEW_IMAGE WM_USER + 1015
#define UM_SKINPANE_DROPITEM WM_USER + 1016
#define UM_SKINPANE_DROPMOVEITEM WM_USER + 1017
#define UM_SKINPANE_DBLCLICKITEM WM_USER + 1022

#define UM_SOUNDPANE_DROPITEM WM_USER + 1020
#define UM_SOUNDPANE_DROPMOVEITEM WM_USER + 1021

// BrushPaneView
#define UM_BRUSHPANE_UPDATE_USE_BUTTON WM_USER + 1014
// LayerPaneView
#define UM_LAYERPANE_CHANGE_LAYER WM_USER + 1010

// Manager Explorer
#define UM_EXPLORER_CHANGE_FOLDER WM_USER + 1011
#define UM_EXPLORER_CHANGE_FOLDER_NAME WM_USER + 1012
#define UM_EXPLORER_MOVE_FILE WM_USER + 1013

#define UM_PROPERTY_PANE_SET_MODIFY WM_USER + 1018

#define UM_EVENT_PANE_CONTROL_CHANGED WM_USER + 1027
#define UM_EVENT_PANE_SELCHANGED WM_USER + 1019
#define UM_EVENT_PANE_REFRESH_INFO WM_USER + 1030

#define UM_SOUNDLIST_PANE_SELCHANGED WM_USER + 1023
#define UM_SOUNDLIST_PANE_ADDSOUNDENVI WM_USER + 1024

#define UM_ENABLE_PANE_VIEW WM_USER + 1025
#define UM_TRIGGERPROP_PANE_PICK_OBJECT WM_USER + 1026

#define UM_WATER_PANE_SELECTRIVER WM_USER + 1032

#define UM_GRIDPANE_CHANGECAMERA WM_USER + 1050
#define UM_GRIDLISTPANE_SELECT WM_USER + 1051